### ISSUE TITLE
Only 1 Hit Door

### ISSUE THREAD

**Issue by DHStyle541** [Nyxchrono/LC.DoorBreach#2]
Hi, using "KeysLockDoors" i mean locked door using key make the door only 1 hit. 
but if from generate totaly normal, i hope no conflict or Compatible also with "KeysLockDoors" Need hit so many times like same config

**Comment by Nyxchrono** [comment]
Thank you for thoughts and or suggestion(s)!

I am not sure what you mean here. If you are referencing a mod, can you provide me a link to the package on the Thunderstore?

**Comment by DHStyle541** [comment]
https://thunderstore.io/c/lethal-company/p/Sophisticasean/KeysLockDoors/

Normally you have to hit it up to 10 times, but when you lock the door you only hit it once, the door immediately opens but not 10 times.

**Comment by Nyxchrono** [comment]
Ah, so what you're saying is that if a door starts out unlocked, but then you lock it with the mod you linked, the door will only take one hit to open?

**Comment by DHStyle541** [comment]
Normal Door
https://github.com/Nyxchrono/LC.DoorBreach/assets/154591650/50eda9cd-2f8e-45de-8f85-e3996a62a6e9

Lock Using Mod
https://github.com/Nyxchrono/LC.DoorBreach/assets/154591650/29c74968-3409-460b-8611-4d83b80cfc30

^ i mean make it like normal door need 10 hits

**Comment by Nyxchrono** [comment]
Oh, I see the issue here. You've re-locked a previously hit door, and the next hit instantly opens it. Is that correct?
I've also just done some testing and I think I've solved this issue and will post an update soon.

**Comment by DHStyle541** [comment]
Yes that what i talking about :))

fk i hate eng word :((((((((

**Comment by Nyxchrono** [comment]
@DHStyle541 Let me know if the update I just pushed out fixes the issue. :)

**Comment by Nyxchrono** [comment]
As no response has been given in two weeks, I am closing this issue as resolved.
